SH = /bin/sh
LIBMODS ?= cfg db lib log path str test

# -- main targets

.PHONY: all
all: build

.PHONY: build
build: build-libmods

.PHONY: clean
clean:
	@rm -rfv build1

# -- util/helper targets

.PHONY: build-libmods
build-libmods:
	@(for mod in $(LIBMODS); do \
		mkdir -vp $(PWD)/build1/lib/$$mod; \
		$(MAKE) -C $(PWD)/build1/lib/$$mod \
			-f $(PWD)/mk1/build.libmod.mk build; \
	done)

# -- __mkcheck is only used for development purposes
# -- self check makefiles with both BSD and GNU make tools (prefer BSD stdout)
GNUMAKE_FILTER ?= >/dev/null
MKTGT ?= all
.PHONY: __mkcheck
__mkcheck:
	@echo "--- GNU make start"
	@gmake -f Makefile.1 $(MKTGT) $(GNUMAKE_FILTER)
	@echo "--- GNU make end"
	@echo "--- BSD make start"
	@make -f Makefile.1 $(MKTGT)
	@echo "--- BSD make end"
