include mk1/vars.mk

# -- main targets

.PHONY: all
all: build

.PHONY: build
build: build-libmods
	@(cd lib && $(MAKE) -f Makefile.1 build)

.PHONY: clean
clean:
	@rm -rfv build1

# -- util/helper targets

.PHONY: build-libmods
build-libmods:
	@(for mod in $(LIBMODS); do \
		mkdir -vp $(PWD)/$(BUILDDIR_NAME)/lib/$$mod; \
		(cd lib/$$mod && $(MAKE) -f Makefile.1 build); \
	done)

# -- __mkcheck is only used for development purposes
# -- self check makefiles with both BSD and GNU make tools (prefer BSD stdout)
MKTGT ?= all
.PHONY: __mkcheck
__mkcheck:
	@echo "--- GNU make start"
	@gmake -f Makefile.1 $(MKTGT) >/dev/null || true
	@echo "--- GNU make end"
	@echo "--- BSD make start"
	@make -f Makefile.1 $(MKTGT)
	@echo "--- BSD make end"
