.PHONY: all
all:
	@$(MAKE) -C path build


.PHONY: clean
clean:
	@$(MAKE) -C path clean


.PHONY: depend
depend:
	@$(MAKE) -C path depend


.PHONY: clean-depend
clean-depend:
	@$(MAKE) -C path clean-depend
